### ISSUE TITLE
Stability & usability issues

### ISSUE THREAD

**Issue by dbolkensteyn** [neurolien/neurolien#4]
* [x] Width of the app not growing with larger screen sizes: it is fixed
* [x] Height: on mobile phones, it'd be great for the 2 buttons to be immediately visible
* [x] Opening https://neurolien.ch/auth directly doesn't work: the button shows an error, and this message appears in the console: `FirebaseError: Firebase: No Firebase App '[DEFAULT]' has been created - call initializeApp()`
* [x] Phone verification: Instead of showing alerts, standard form error handling could be used (i.e. show in red)
* [x] More action oriented error messages could be shown to users
* [x] On iOS Brave, the border of the phone's input box is not being shown
* [x] Usability: The phone input could be split in 2, one country selector, and one for the number, as the `+..` format is required (`00...` is not supported)
* [ ] Recaptcha should be disabled if possible, as it leads to errors such as `FirebaseError: auth/captcha-check-failed` and `FirebaseError: auth/too-many-requests`
* [x] Save a GPS coordinate in addition to the textual `city` in the DB to allow further processing (based on what Google APIs allow)
* [x] Restore the previously saved values back from the form when a user logs back in
* [x] Switch SMS messages from spanish to french or device language
* [x] Accessing https://neurolien.ch/consult/main without being authenticate should redirect to the homepage

**Comment by billdevmaster** [comment]
I resolved almost of them.
I left recaptcha, because the recaptcah is necessary for firebase phone auth.
please check these links.
https://firebase.google.com/docs/auth/web/phone-auth
https://stackoverflow.com/questions/63793482/how-to-use-firebase-phone-authentication-without-recaptcha-in-react-native

**Comment by dbolkensteyn** [comment]
The phone input doesn't seem to be working well:

1. The text is white on white => I can't read what I wrote
2. Even if I input my actual phone number, it says it's invalid and I cannot proceed
3. In the dev tools, there is a 400 bad request error

<img width="408" alt="Screenshot 2023-09-25 at 10 16 19" src="https://github.com/neurolien/neurolien/assets/1132601/652301cf-0ef8-4d9c-9c20-880245cbc23a">
<img width="475" alt="Screenshot 2023-09-25 at 10 16 45" src="https://github.com/neurolien/neurolien/assets/1132601/83e78d76-6691-4d10-943f-43ce3c41ccbd">
<img width="1056" alt="Screenshot 2023-09-25 at 10 22 53" src="https://github.com/neurolien/neurolien/assets/1132601/423af5a2-1779-4c7f-b53d-3dcf8d7cb12d">

**Comment by billdevmaster** [comment]
well. let me check it.

**Comment by dbolkensteyn** [comment]
On mobile it looks better, but the phone number validation fails as well.

**Comment by billdevmaster** [comment]
the view is okay?
only phone number validation is not working?

**Comment by billdevmaster** [comment]
fixed it.
the issue was caused, because our domain neurolien.ch was not added to firebase authorised domain list.
I just added and it worked well now.

**Comment by billdevmaster** [comment]
Hello.
Could you let me know your feedback of this issues again?

**Comment by dbolkensteyn** [comment]
👋  @billdevmaster 

Can you send me a screenshot of how the phone number input looks for?

For me it still looks like white on white (both Brave and Chrome desktop):
<img width="410" alt="Screenshot 2023-09-26 at 14 58 36" src="https://github.com/neurolien/neurolien/assets/1132601/3f83a562-75f9-4735-bed3-53acb4b0cb3d">

**Comment by billdevmaster** [comment]
Could you let me know your iphone version?

**Comment by dbolkensteyn** [comment]
This is on desktop @billdevmaster 
1. Brave: Version 1.58.131 Chromium: 117.0.5938.92 (Official Build) (arm64)
2. Chrome: Version 116.0.5845.187 (Official Build) (arm64)

**Comment by dbolkensteyn** [comment]
Also, I am still able to reach https://neurolien.ch/consult/main without being authenticated. It doesn't send me back to the auth screen.

If I try to submit the form, i get this error in the console:

<img width="1274" alt="Screenshot 2023-09-26 at 15 02 56" src="https://github.com/neurolien/neurolien/assets/1132601/1d9ba736-9edb-4d78-989b-f0edee9bfe69">

**Comment by dbolkensteyn** [comment]
The SMS confirmation code is also not coming in the language of the browser

**Comment by dbolkensteyn** [comment]
Closing in favor of https://github.com/neurolien/neurolien/issues/4
